# Generated by Django 5.0 on 2024-03-11 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_number', models.CharField(help_text='<em>10 / 13 / 17</em> digits format', max_length=17, unique=True, verbose_name='NID Number')),
                ('date_of_birth', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('account_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], help_text='<em>Choice Your role Patient or Doctor</em>', max_length=10)),
                ('image', models.ImageField(upload_to='account/media/images/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
