# Generated by Django 5.0 on 2024-03-16 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_dose_date', models.DateField(blank=True, default=None, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('AstraZeneca', 'AstraZeneca'), ('Pfizer', 'Pfizer'), ('Sinopharm', 'Sinopharm'), ('Moderna', 'Moderna')], max_length=20)),
                ('description', models.TextField()),
                ('dose_number', models.IntegerField(default=1)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaign/media/images/')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(choices=[('250 Bedded General Hospital Khulna', '250 Bedded General Hospital Khulna'), ('Shaheed Sheikh Abu Naser Specialized Hospital', 'Shaheed Sheikh Abu Naser Specialized Hospital')], max_length=100)),
                ('campaigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
                ('vaccine', models.ManyToManyField(to='campaign.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('dose_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaign.dosebooking')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaign.vaccinecampaign')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='dosebooking',
            name='first_dose_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.vaccineschedule'),
        ),
    ]
