# Generated by Django 5.0 on 2024-03-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dose_booking',
        ),
        migrations.AddField(
            model_name='dosebooking',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.vaccinecampaign'),
        ),
    ]
