# Generated by Django 5.0 on 2024-03-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_review_dose_booking_dosebooking_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosebooking',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dose_book', to='campaign.vaccinecampaign'),
        ),
    ]
