# Generated by Django 5.0 on 2024-03-18 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_dosebooking_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosebooking',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.vaccinecampaign'),
        ),
    ]
