# Generated by Django 5.0 on 2024-03-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosebooking',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.CharField(choices=[('AstraZeneca', 'AstraZeneca'), ('Pfizer', 'Pfizer'), ('Sinopharm', 'Sinopharm'), ('Moderna', 'Moderna'), ('Sinovac', 'Sinovac')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccinecampaign',
            name='place',
            field=models.CharField(choices=[('250 Bedded General Hospital Khulna', '250 Bedded General Hospital Khulna'), ('General Hospital Khulna', 'General Hospital Khulna'), ('Khulna City Medical College Hospital', 'Khulna City Medical College Hospital'), ('Doctors Point Specialized Hospital Khulna', 'Doctors Point Specialized Hospital Khulna'), ('Gazi Medical College Hospital Khulna', 'Gazi Medical College Hospital Khulna'), ('Shaheed Sheikh Abu Naser Specialized Hospital', 'Shaheed Sheikh Abu Naser Specialized Hospital')], max_length=100),
        ),
    ]
