# Generated by Django 5.0 on 2024-03-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_dosebooking_vaccine_alter_vaccine_vaccine_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
